01 fix base build

diff --git a/infra/base-images/base-builder/compile b/infra/base-images/base-builder/compile
--- a/infra/base-images/base-builder/compile
+++ b/infra/base-images/base-builder/compile
@@ -133,16 +133,16 @@ else
 #    cat $TMP_DIR/BBtargets.txt
 #    popd > /dev/null
      cat $SRC/BBtargets.txt >>  $TMP_DIR/BBtargets.txt
-     echo "BBtargets's content is as follow"
+     echo -e "BBtargets's content is as follow\n"
      cat $TMP_DIR/BBtargets.txt
 
-    if [ $(cat $TMP_DIR/BBtargets.txt | wc -l) -eq 0 ]; then
-      echo    "############################################################################"
-      echo -e "# \e[1;31mAborting ..\e[0m -- No changed source <files> in commit of $PROJECT."
-      echo    "############################################################################"
-      rm -rf $TMP_DIR
-      exit 1
-    fi
+#    if [ $(cat $TMP_DIR/BBtargets.txt | wc -l) -eq 0 ]; then
+#      echo    "############################################################################"
+#      echo -e "# \e[1;31mAborting ..\e[0m -- No changed source <files> in commit of $PROJECT."
+#      echo    "############################################################################"
+#      rm -rf $TMP_DIR
+#      exit 1
+#    fi
   fi
 fi
 
